### PR TITLE
enhanced investment account handling

### PR DESCRIPTION
**Pull request by jeffjl74**
Adds support for investment account cash balances, cash transfers, security balances, bond transactions, options transactions, and 401k accounts.

Nearly all of the changes just add functionality like additional structure members and should not cause any backward compatibility issues.

But, one change to current behavior is to correct the handling of INVBANKTRAN. Previous versions generate a bank transaction container instead of an investment transaction container.

Another behavior change is the handling of TRANSFER. Previous versions generate extraneous account and/or statement callbacks in response to a TRANSFER.

A little more detailed summary of the changes is provided in the NEWS file. 

It looks like about half the diff views below are just some test files I created from samples in the OFX spec, which hopefully don't require much of your review time.

I only build on Windows, so there might be some issues unknown to me on other build systems.

I spent quite a bit of time on ofxdump. It is probably the easiest way to test the new features.

I've been using these changes on a locally modified version of KMyMoney for about a couple of years.  But in fixing TRANSFER, I had broken ACCTINFOTRNRS. I've been just living with that since I hardly ever need it. I only just recently decided to get everything fixed, updated to the latest github master, and made a fork. So here it is, in case anyone else is interested.

### CODE REVIEW

**Comment by genterminl** [comment]
Thanks for this!  I was about to file a new issue, and fortunately found this PR first.  (I'm using KMyMoney, and it doesn't remember the date of last online update of an investment account due to libOFX not dealing with INVTRANLIST, which it looks like is part of this PR.)  However, applying this diff to 0.9.13, I get 

In file included from /usr/portage/tmpdir/portage/dev-libs/libofx-0.9.13-r1/work/libofx-0.9.13/ofx2qif/ofx2qif.c:44:0:
../inc/libofx.h:417:5: error: unknown type name 'bool'
     bool amounts_are_foreign_currency;
     ^~~~

I'm on Gentoo Linux, with gcc 7.3.0, and have had no previous issues compiling libOFX.  I"m hoping this is just some simple configuration issue on my part, but I'm stumped for now.

**Comment by jeffjl74** [comment]
Hmm. "bool" is used elsewhere in libofx itself, but it looks like I introduced it for the first time into libofx.h. I see 5 of them in libofx.h (and libofx.h.in). If you want to try to patch it, they could easily be changed to "int", or ofx2qif.c could include whatever it is that defines "bool".

I'll look at fixing the fork (I'd change from bool to int in the .h).

**Comment by jralls** [comment]
Yes, libofx.h is included in C files so it can't use C++ and the bool type is C++. Int is a suitable substitute, unsigned int would be slightly better.

**Comment by genterminl** [comment]
Apologies for being difficult, and thanks for the patch, but I still get redeclaration errors:

../inc/libofx.h:1229:10: error: nested redefinition of 'enum Inv401kSource'
../inc/libofx.h:1229:10: error: redeclaration of 'enum Inv401kSource'
../inc/libofx.h:1231:7: error: redeclaration of enumerator 'OFX_401K_SOURCE_PRETAX'
also for the remaining enumerators.

I see the two enums are in different structs (OfxTransactionData and OfxPositionData) but they do not look nested to me, so I'm not sure why gcc is complaining.

**Comment by jralls** [comment]
gcc is complaining because it's gcc, not g++. All types in C are global.

**Comment by jeffjl74** [comment]
I changed it to make each enum different.

**Comment by genterminl** [comment]
Thanks again.  I had other errors, but not on a repeat try, so I blame them on an unclean build environment.  Now I'll have to see what KMyMoney can do with the new results.

**Comment by genterminl** [comment]
I'll wait for the KMM developer to confirm, but with this PR applied to 0.9.13, KMyMoney is now able to correctly set the last update date of an investment account (using DTEND from INVTRANLIST) so that's one definite positive result.

**Comment by jeffjl74** [comment]
I've made changes to my local build of KMM 4.8 to incorporate a bunch of the data provided by my version of libofx. My KMM now verifies that it has the same cash balance, same share balance, asks to insert a balancing share transaction if the share balances differ, handles bond trades including accrued interest, handles options trades including standardization of option symbols via a per-broker regex, handles short sells, and handles cash transactions between the KMM "brokerage account" and the investment account.  If they ever get to a point where KMM 5 will work on Windows, and libofx gets updated, I expect to provide some input to KMM.

**Comment by genterminl** [comment]
We seriously hope that 5.0.2 (code freeze this week, I think) will include a Windows release.  I have actually successfully built KMM on Windows 10 with Craft (and all dependencies).   I don't have the links, but I believe there are daily builds on the KDE automated build systems, but for master, not the 5.0 branch.  They are close, but not identical.

**Comment by ostroffjh** [comment]
I just submitted a version bump request for Gento, and discovered that although vanilla 0.9.13 builds fine for me, with these three patches, build fails with

make  ofxconnect
make[3]: Entering directory '/usr/portage/tmpdir/portage/dev-libs/libofx-0.9.13-r1/work/libofx-0.9.13_build/ofxconnect'
/bin/sh ../libtool  --tag=CXX   --mode=link x86_64-pc-linux-gnu-g++  -O2 -pipe -std=c++11  -Wl,-O1 -Wl,--as-needed -o ofxconnect cmdline.o nodeparser.o ofxpartner.o ofxconnect.o ../lib/l
ibofx.la -lcurl -lssh2 -lssh2 -lssl -lcrypto -lssl -lcrypto -lz -lxml++-2.6 -lxml2 -lglibmm-2.4 -lgobject-2.0 -lglib-2.0 -lsigc-2.0  
libtool: link: x86_64-pc-linux-gnu-g++ -O2 -pipe -std=c++11 -Wl,-O1 -o .libs/ofxconnect cmdline.o nodeparser.o ofxpartner.o ofxconnect.o  -Wl,--as-needed ../lib/.libs/libofx.so -L/usr/li
b -losp -lcurl -lssh2 -lssl -lcrypto -lz -lxml++-2.6 -lxml2 -lglibmm-2.4 -lgobject-2.0 -lglib-2.0 -lsigc-2.0
ofxpartner.o: file not recognized: File truncated

Oddly, just going to the build dir and manually typing "make" has no errors.  So - I don't know if I have a strange build configuration or if there is something funny with how Gentoo does the build (not that I can tell) or if it just fails the first time but not subsequently.

**Comment by benoitg** [comment]
Merged through cherry-pick, except for the ofxdump command line arguments changes.

**Comment by jeffjl74** [comment]
Deleted after merge

**Pull request closed without merging**
