### PR TITLE
Update FindOpenSP; also allow to forcefully ENABLE SP_MULTI_BYTE

### LINKED ISSUE #70: Still slightly confused about SP_MULTI_BYTE usage
See the code I came up with at: https://github.com/libofx/libofx/blob/28afdfaa785cc6f2aa7ef0f036fdd96cc6be765c/CMakeLists.txt#L109

It checks whether the OpenSP's `config.h` has `#define SP_MULTI_BYTE 1`. I based that on the `config.h` files from the distributions I came across. 

However, I noticed that the OpenSP itself doesn't check its value, but rather presence only, so I suppose there's a chance that a `config.h` might exist out there that does `#define SP_MULTI_BYTE` only, which the aforementioned code would actually ignore and assume it was, in fact, undefined.. 

Rather unlikely, but worth taking into consideration.

For what it's worth, I am working on upstreaming the FindOpenSP module (https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7470), hence this mind-wandering.

### PR DESCRIPTION
**Pull request by wrobelda**
Fixes #70 

This is basically ready, but I expect further changes to `FindOpenSP` module, as its review is in progress at https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7470

### CODE REVIEW

**Comment by cstim** [comment]
Code looks fine so far. Feel free to mention when you're ready to have it merged.

**Comment by wrobelda** [comment]
> Code looks fine so far. Feel free to mention when you're ready to have it merged.

Will do!

**Comment by wrobelda** [comment]
@cstim FindOpenSP was just merged upstream without further adjustments, so this is ready to be merged as well.

**Comment by wrobelda** [comment]
@cstim once this is merged, hopefully a new release can be made? This would be useful as I still have a pending PR for vcpkg port for libofx, and ideally would want to upstream it without any additional CMake patches .

**Pull request merged**
